# Jekyll Customizations
exclude: ['Gemfile', 'Gemfile.lock', 'Guardfile', 'config.ru', 'README.md', 'Procfile', 'vendor', 'gems']
source: 'site'
destination: 'public'
relative_permalinks: true
permalink: pretty
permalink: /blog/:title


# Default Jekyll Config
markdown: redcarpet
pygments: true